site_name: GPT-X
site_url: https://sambradley-rsm.github.io/gpt-x-docs/
theme:
  name: material
  logo: assets/RSM_White.svg
  palette:
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - header.autolink
    - navigation.tracking
    - navigation.sections

nav:
  - Overview: index.md
  - Architecture: components.md
  - Installation: installation.md
  - User Guide: user-guide.md
  - FAQ: faq.md
  - Azure Innovate Assessment: azure-innovate.md
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format